### ISSUE TITLE
Exception when using properties with type Dictionary<string, string>

### ISSUE THREAD

**Issue by edjo23** [Avanade/Beef#131]
Hi,

We are getting the following exception when trying to use a Dictionary<string, string> property on an entity with an ObjectToJsonConverter db mapper to transform the dictionary to a JSON string for storage into a SQL database.

```
System.TypeInitializationException: The type initializer for 'Beef.Data.Database.DatabaseMapper`2' threw an exception.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Type 'OurEntity' Property 'Metadata' is an ICollection<> however no Add method could be found. (Parameter 'pi')
   at Beef.Reflection.ComplexTypeReflector.Create(PropertyInfo pi)
   at Beef.Mapper.PropertyMapperCustomBase`2..ctor(Expression`1 srcePropertyExpression, String destPropertyName, OperationTypes operationTypes)
   at Beef.Data.Database.DatabasePropertyMapper`2..ctor(Expression`1 srcePropertyExpression, String destColumnName, OperationTypes operationTypes)
   at Beef.Data.Database.DatabaseMapper`1.Property[TSrceProperty](Expression`1 srcePropertyExpression, String columnName, OperationTypes operationTypes)
```

Our property configuration.

```
<Entity Name="OurEntity">
    <Property Name="Metadata" Type="Dictionary&lt;string,string&gt;" DataConverter="ObjectToJsonConverter" IsDataConverterGeneric="true" />
</Entity>
```

Generates this mapper, the exception is being thrown by the call to `Property(s => s.Metadata)`.

```
public partial class DbMapper : DatabaseMapper<OurEntity, DbMapper>
{
    public DbMapper()
    {
        Property(s => s.Metadata).SetConverter(ObjectToJsonConverter<Dictionary<string,string>>.Default!);
        AddStandardProperties();
        DbMapperCtor();
    }
}
```

As a work around we tried wrapping the dictionary property with a non-collection object. This got around the db mapping issue but we got a similar exception thrown by the constructor of `WebApiPatch` in our patch operation.

```
"System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Type 'OurWrapper' Property 'Metadata' is an ICollection<> however no Add method could be found. (Parameter 'pi')
   at Beef.Reflection.ComplexTypeReflector.Create(PropertyInfo pi)
   at Beef.Reflection.PropertyReflector`2..ctor(EntityReflectorArgs args, Expression`1 propertyExpression)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at Beef.Reflection.EntityReflector`1..ctor(EntityReflectorArgs args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at Beef.Reflection.EntityReflectorArgs.<>c__DisplayClass26_0.<GetReflector>b__0(Type _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Beef.Reflection.EntityReflectorArgs.GetReflector(Type type)
   at Beef.Reflection.PropertyReflector`2.GetEntityReflector()
   at Beef.Json.JsonEntityMerge.MergeApplyComplex(JsonEntityMergeArgs args, IPropertyReflector pr, JProperty jp, Object entity)
   at Beef.Json.JsonEntityMerge.MergeApply(JsonEntityMergeArgs args, IEntityReflector er, JToken json, Object entity)
   at Beef.Json.JsonEntityMerge.MergeApplyComplexItems(JsonEntityMergeArgs args, IPropertyReflector pr, JProperty jp, Object entity)
   at Beef.Json.JsonEntityMerge.MergeApplyComplex(JsonEntityMergeArgs args, IPropertyReflector pr, JProperty jp, Object entity)
   at Beef.Json.JsonEntityMerge.MergeApply(JsonEntityMergeArgs args, IEntityReflector er, JToken json, Object entity)
   at Beef.Json.JsonEntityMerge.Merge[TEntity](JToken json, TEntity value, JsonEntityMergeArgs args)
   at Beef.AspNetCore.WebApi.WebApiPatch`1.UpdateUsingMergePatchAsync(ActionContext context, T value)
   at Beef.AspNetCore.WebApi.WebApiPatch`1.ExecuteResultAsyncInternal(ActionContext context, Func`2 func)
   at Beef.AspNetCore.WebApi.WebApiPatch`1.ExecuteResultAsyncInternal(ActionContext context, Func`2 func)
   at Beef.InvokerBase`1.WrapInvokeAsync(Object caller, Func`1 func, TParam param, String memberName, String filePath, Int32 lineNumber)
   at Beef.InvokerBase`1.InvokeAsync(Object caller, Func`1 func, TParam param, String memberName, String filePath, Int32 lineNumber)
```

Any chance that `Beef.Reflection.ComplexTypeReflector` could be updated to support Dictionaries? Thanks.

**Comment by chullybun** [comment]
Hi @edjo23, fix made within latest NuGet package Beef.Core v4.1.13. Have a go and let me know how you get on. Cheers...

**Comment by edjo23** [comment]
Awesome, thanks @chullybun, I'll check it out.

**Comment by edjo23** [comment]
Hi @chullybun, this is now working for us. Thanks again.
