### ISSUE TITLE
Test fails: 'The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached'

### ISSUE THREAD

**Issue by karamem0** [Avanade/Beef#200]
I am testing the API generated by Beef with test code. I have many test methods, but when I run all the tests, I find that some of them fail.

The error message is:

```
Error Message:
  System.IO.IOException : The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
Stack Trace:
  at System.IO.FileSystemWatcher.StartRaisingEvents()
  at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
  at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
  at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
  at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
  at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
  at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
  at Beef.Test.NUnit.AgentTester.BuildConfiguration[TStartup](String environmentVariablePrefix, String environment)
```

[I have found that enabling appsetting.json reload causes problems](https://github.com/dotnet/AspNetCore.Docs/issues/19814). However, the `reloadOnChange` parameter is hidden by the Beef framework and cannot be changed.

**Comment by chullybun** [comment]
@karamem0, I will look to update such that `reloadOnChange` is set to `false`; I can't think of a reason to have set to `true` or support a means to override. This is a `v4.2.x` issue only.

**Comment by chullybun** [comment]
@karamem0, ended up going down the parameter overload route - you'll need to update your test code similar to the following:

```csharp
var config = AgentTester.BuildConfiguration<Startup>("Beef", reloadOnChange: false);
```

Published new `Beef.Test.NUnit` package, version `4.2.8`.

Can you please confirm that this resolves your issue, thanks.

**Comment by karamem0** [comment]
Many thanks! This is very valuable to me.
