### ISSUE TITLE
Change to use parallel prefetching of reference data is throwing an exception

### ISSUE THREAD

**Issue by edjo23** [Avanade/Beef#44]
Hi. We are in the process of upgrading our Beef packages to version 3 packages. After upgrading we have hit an issue with a change to the generated code for the ReferenceDataProvider.

This maybe a follow on from issue #41.

This generated code for the ReferenceDataProvider, that uses Parallel.ForEach:
```c#
        public override Task PrefetchAsync(params string[] names)
        {
            var types = new List<Type>();
            if (names == null)
            {
                types.AddRange(GetAllTypes());
            }
            else
            {
                foreach (string name in names.Distinct())
                {
                    switch (name)
                    {
                        case var n when string.Compare(n, nameof(RefDataNamespace.RefDataA), StringComparison.InvariantCultureIgnoreCase) == 0: types.Add(typeof(RefDataNamespace.RefDataA)); break;
                        // Removed 10 case statements for beverity
                    }
                }
            }

            Parallel.ForEach(types, (type, state) => { var x = this[type]; });
            return Task.CompletedTask;
        }
```

In this test:
```c#
        [Test]
        [AgentTester(TestUser.Admin)]
        public void GetNamed_All()
        {
            var names = ReferenceData.Current.GetAllTypes().Select(x => x.Name).ToArray();

            var r = AgentTester.Create<ReferenceDataAgent>()
                .ExpectStatusCode(HttpStatusCode.OK)
                .Run((a) => a.Agent.GetNamedAsync(names));

            Assert.NotNull(r.Content);
            Assert.AreEqual(JObject.Parse("{ \"content\":" + r.Content + "}")["content"].Children().Count(), names.Length);
        }
```

Throws this exception:
```
An unexpected internal server error has occurred. Exception: System.AggregateException: One or more errors occurred. (Invalid operation. The connection is closed.) (Invalid operation. The connection is closed.)
 ---> System.InvalidOperationException: Invalid operation. The connection is closed.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Beef.Data.Database.DatabaseCommand.<>c__DisplayClass34_0.<<DbDataReaderWrapperNoResultAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Beef.Data.Database.DatabaseInvoker.WrapInvokeAsync(Object caller, Func`1 func, DatabaseBase param, String memberName, String filePath, Int32 lineNumber)
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
```

If we modify the generated code to iterate the types in sequence then this works as expected and our test passes.

**Comment by chullybun** [comment]
The `ExecutionContext` flows from thread-to-thread. The database connection management is orchestrated using a `Stack`- so when assessed concurrently across multiple threads the order in which it is popped may result in the wrong connection being closed. To alleviate a new ExecutionContext.FlowSuppression has been added to stop the flow, then a new (copy) `ExecutionContext` is created to enable (via `ExecutionContextFlow.SetExecutionContext`). The reference data code generation has been updated to enable.

**Comment by chullybun** [comment]
Thanks for the note. I have updated the code generation to include the `Beef` namespace declaration. New NuGet package has been published.

**Comment by edjo23** [comment]
Thanks @chullybun, that worked for us. FYI all of our tests are now passing.
